---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug # using it in debug mode
    args: ["--context=git://github.com/ezzat223/kaniko-demo", # context is where the source code lies
            "--destination=ezzat22/devops-toolkit:1.0.0"] # where to push the image
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json

